apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: todolist
data:
  DATABASE_HOST: "10.0.3.11"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "proddb"
  PORT: "5000"
  NODE_ENV: "production"